[build]
  publish = "."
  command = "echo 'Static deployment'"

[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/calculatormediefacultate.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
