[build]
  publish = "dist"
  command = "node netlify-build-final.js || node netlify-simple.js"

[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/calculatormediefacultate.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--silent"
  VITE_BUILD_TIMEOUT = "600"
  VITE_GA_MEASUREMENT_ID = "G-PLACEHOLDER"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"